global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'
  group_wait: 2m
  group_interval: 2m
  repeat_interval: 2m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: ''
        channel: '#stage-logs'
        send_resolved: true

