version: '3.8'

services:
  cadvisor:
    image: docker.arvancloud.ir/google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/kmsg:/dev/kmsg:ro
    restart: always

  prometheus:
    image: docker.arvancloud.ir/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "7010:9090"
    restart: always

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: docker.arvancloud.ir/prom/alertmanager:latest
    container_name: alertmanager
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always

  node_exporter:
    image: docker.arvancloud.ir/prom/node-exporter:latest
    container_name: node_exporter
    restart: always

  grafana:
    image: docker.arvancloud.ir/grafana/grafana:latest
    container_name: grafana
    ports:
      - "7012:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    restart: always

volumes:
  prometheus_data:
  grafana-data:

